name: Publish prereleases

on: pull_request

jobs:
  release:
    if: ${{ github.repository_owner == 'opennextjs' }}
    name: Publish builder package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.10.0

      - name: Install Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
          registry-url: "https://registry.npmjs.org"

      - name: Install Dependencies
        run: pnpm i --frozen-lockfile

      - name: Build
        run: pnpm -F cloudflare run build

      - name: Publish to NPM
        run: pnpm exec pkg-pr-new publish --pnpm --compact './packages/cloudflare'
